### ISSUE TITLE
Confidant needs to provide a way to pass environment variables to every configure.js

### ISSUE THREAD

**Issue by rickychien** [gaye/confidant#28]
@gaye 

According to README.md: 

```
Confidant will scan the filesystem rooted at the directory from which it is run for files named configure.js
```

thus, if we want to launch build system like this

```
confidant dir DEBUG=1 DEVICE_TYPE=phone
```

These ENVs such as DEBUG=1,  DEVICE_TYPE=phone have to pass into every configure.js, and each configure.js runs on different `node -e` will mean inside different process. For being able to communicate ENVs within configure.js, these is my solution:

Pass every necessary environment variables while invoking `node -e` in build.ninja. That could increase length of build.ninja because you may see like this:

```
rule rule-0
command = cd /Users/Ricky/Documents/confidant/test/fixtures/config_filter && node -e VARIABLE1=xxx VARIABLE2=xxx VARIABLE3=xxx "// source code ..."
```

Debuggability is still a problem if we want to trace into build.ninja file, but I am going to do this if you feel ok :)

**Comment by lambdabaa** [comment]
Sounds good to me!

**Comment by lambdabaa** [comment]
++

**Comment by rickychien** [comment]
#31
