### ISSUE TITLE
v0.4.0 caused some regression

### ISSUE THREAD

**Issue by lambdabaa** [gaye/confidant#35]
Seeing a lot of

```
install: invalid option -- 'e'
Try 'install --help' for more information.
ninja: build stopped: subcommand failed.
```

**Comment by lambdabaa** [comment]
Will add a test case shortly...

**Comment by lambdabaa** [comment]
@rickychien Haven't found time to write test case yet, but you may want to take a look

**Comment by gaye** [comment]
I created a branch called `0.3.x` where I'm adding some minor fixes in the meantime.
